apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alert
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: pod-restarts
    rules:
    - alert: PodRestartHigh
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 3
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High Pod Restart Detected"
        description: "Pod restarted more than 3 times in 5 minutes."